@extends('layouts.farmersmarket-head')
@include('layouts.main-nav')
@include('farmersmarket.users-all')
@include('farmersmarket.farmersmarket-users-location')
@include('farmersmarket.farmersmarket-products')
@include('farmersmarket.farmersmarket-products-tag')
@include('layouts.farmersmarket-footer')